### ISSUE TITLE
Returning author data?

### ISSUE THREAD

**Issue by nicholaskemery** [massimoaria/dimensionsR#3]
I am not sure how to access certain author data using this package. 1) how do I change a search "in title_abstract_only" to "in authors"? 2) How can I return Dimensions author ID numbers of the form "ur.[numeric string]"? I can only return publication ID numbers of the form "PUB.[numeric string]." Thank you!

**Comment by massimoaria** [comment]
The function dsQueryBuild() helps you to define a valid query in the DSL language in an automatic way. For the moment, the function provides support limited to search by topics.
You can still use the package to download a collection searching by authors. But, in this case, you have to write a valid query (using the DSL language, https://docs.dimensions.ai/dsl/language.html) by yourself and pass it to the function dsApiRequest().
